added docstrings
Sunchasing/chache pull request #1
Opened 2021-05-13 19:19 UTC by Sunchasing

2021-05-13 19:40 UTC, zkscpqm requested changes
Mostly ok, some semantics and some things are incorrect

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        :param max_size: The maximum number of cacheables to store
Include the info that None=infinite

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        Instantiates the Cache class for the decorated function
Include the fact that if it already exists, we don't re-create it, therefore persistency

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        :return: The decorated function
Don't you mean the function's cache..?

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        Injects cacheable functions into the passed function.
1. Be more explicit. It's not just a decorator, it's the API for your whole module.
2. It injects not only cacheable methods but also cache methods to the wrapper

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        Creates a cleaner thread that checks if any cacheables should be deleted at set intervals
creates and starts**

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        Gets the value stored in a cacheable and updates the links between in, the lru and the mru.
no need to be so specific

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        Pops the specified cacheable
Maybe include what pop is (get + delete)

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        :return: Statistics
this can probably just be part of the :return: definition, not separate

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
>          while new_size < self.size:
Come to think of it, this would fail if we set max size to None. Maybe we should handle that

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        :return: ItemsView of cacheables
you can put the summaries in the :return: definition, but word it like - Returns a view on the keys/values etc. A view is very different than actually returning the items themselves

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        Deletes all expired cacheables
Maybe include the fact that this runs in the secondary thread

2021-05-13 19:40 UTC, zkscpqm commented on src/cacheables/__init__.py
> +    :return: The cacheable type
We don't return the type, we return an instance of that type. This is an object factory

2021-05-13 19:40 UTC, zkscpqm commented on src/cache_lib.py
> +        :return: Statistics
Also, what's included in the statistics? You mentioned it in the cacheable stats but not here

2021-05-13 19:40 UTC, zkscpqm commented on src/cacheables/timed_cacheable.py
> +        :return:
remove this

2021-05-13 19:40 UTC, zkscpqm commented on src/cacheables/timed_cacheable.py
> +        :return:
remove this

2021-05-14 16:59 UTC, Sunchasing commented on src/cacheables/__init__.py
> +    :return: The cacheable type
You're an object factory.

2021-05-14 17:38 UTC, merged